### ISSUE TITLE
hasLimited not working

### ISSUE THREAD

**Issue by swgamerx** [rmmmp/emberfire-utils#14]
Having issues getting hasLimited() to respond with any results. 
`DEBUG: -------------------------------  
DEBUG: Ember: 2.10.2  
DEBUG: Ember Data: 2.11.0  
DEBUG: Firebase: 3.6.5  
DEBUG: EmberFire: 2.0.4  
DEBUG: jQuery: 3.1.1  
DEBUG: -------------------------------`
`import DS from 'ember-data';
import hasLimited from 'emberfire-utils/utils/has-limited';

export default DS.Model.extend({
    name: DS.attr('string'),
    addresses: hasLimited('address', '$id_addresses',  '/admin/company/$id', {limitToFirst: 20}),
    logo: DS.attr('string'),
    addedDate: DS.attr('date'),
    lastUpdated: DS.attr('date')
});`

**Comment by rmmmp** [comment]
Have you tried updating EmberFire to 2.0.6? I don't think the EmberFire 2.0.4 is compatible with Ember Data 2.11.0.

**Comment by rmmmp** [comment]
Closing issue as I'm unable to replicate this and the OP didn't respond anymore. Feel free to reopen this if necessary.
