### ISSUE TITLE
hasLimited() not successfully querying firebase

### ISSUE THREAD

**Issue by swgamerx** [rmmmp/emberfire-utils#21]
Havn't been able to get hasLimited() to work yet. If I use hasMany() then the ember server crashes trying to get the thousands of records. 

`import DS from 'ember-data';
import hasLimited from 'emberfire-utils/utils/has-limited';

export default DS.Model.extend({
    name: DS.attr('string'),
    addresses: hasLimited('address',  {limitToFirst: 20}),
    logo: DS.attr('string'),
    addedDate: DS.attr('date'),
    lastUpdated: DS.attr('date')
});`

**Comment by rmmmp** [comment]
@swgamerx, please don't create duplicate issue. Reuse the issue #14 that you've filed since it's not yet resolved. I also commented a possible solution there. Can you see if it works?
