### ISSUE TITLE
this.get('firebaseUtil') is returning undefined on 1.5.0

### ISSUE THREAD

**Issue by Ghostavio** [rmmmp/emberfire-utils#49]
it works fine on 1.3, it doesn't seem to work on with 1.5
emberfire version: 2.0.7

**Comment by rmmmp** [comment]
@Ghostavio, make sure to inject the service. I removed the part where the service was injected automatically for explicitness.

**Comment by Ghostavio** [comment]
Oh, ok, maybe that should be updated in the readme 😛

**Comment by Ghostavio** [comment]
aaaand it already is, my bad!

>Simply inject the firebase-util service.
