### ISSUE TITLE
Loading more data with query isn't working

### ISSUE THREAD

**Issue by BobrImperator** [rmmmp/emberfire-utils#53]
Ember-data ^2.14
Ember  ^2.14
And
Ember 2.13.4
Ember-data 2.13

I've tried adding infinite scroll for my webpage with few different methods using emberfire/emberfire-utils
and none of them seems to work. Closest would be:
`  model() {
  this.get('store').query('image', {
  limitToFirst: 10
}).then((images) => {
  images.get('firebase').next(10);
});
` but I get an error 

> TypeError: Cannot read property 'next' of undefined

So I tried to figure out what's inside firebase service and it seemed like it needs cacheId, so I added one

`  model() {
  this.get('store').query('image', {
  cacheId: 'hello',
  limitToFirst: 10
}).then((images) => {
  images.get('firebase').next(10);
});`

With that I receive no more errors, but no data either, well it doesn't appear on screen when calling it in .hbs with {{model.name}} but ember inspector says that there are few models loaded.
So then I've tried to do it like this - with utility service

`return firebaseUtil.query('image', {
  cacheId: 'cache_id',
  limitToFirst: 10,
}).then(() => {
  firebaseUtil.next('cache_id', 10);
});`

> TypeError: Cannot read property 'ref' of undefined
> DEPRECATION: You're loading the next records to an old query usage. Please use the new query 
> usage. 

With that it's still not working, so I was messing around with firebaseUtil methods, trying to use _newNext instead of next, and _oldQuery, _newQuery stuff. But I can't get it running. I'm not really experienced programmer, so it is quite a problem to solve for me. I hope it's at least me doing something wrong, and someone could explain how it should be done.

**Comment by rmmmp** [comment]
May I see your template? I may further help with the debugging if I see it.

**Comment by BobrImperator** [comment]
`<div class="layout-row layout-xs-column center">
  <div class="layout-column flex-xs flex-gt-xs-35 ">
    {{#each model as |image|}}
    {{image.Id}}
    {{#paper-card as |card|}}
      {{#card.header as |header|}}
        {{#header.avatar}}
          <img src="{{image.gallery.user.imageUrl}}" alt="tomster" />
        {{/header.avatar}}
        {{#header.text as |text|}}
          {{#text.title}}{{image.gallery.user.name}}{{/text.title}}
        {{/header.text}}
      {{/card.header}}

      {{card.image   src=image.url }}

      {{#card.title as |title|}}
        {{#title.text as |text|}}
          {{#text.headline}}Title{{/text.headline}}
          {{#text.subhead}}Picture's love level {{image.score}} timestamp {{image.timestamp}}  {{/text.subhead}}
        {{/title.text}}
      {{/card.title}}

      {{#card.actions class="layout-row layout-align-start-center" as |actions|}}
        {{#paper-button}}Action 1{{/paper-button}}
        {{#paper-button}}Action 2{{/paper-button}}
        {{#actions.icons}}
          {{#paper-button iconButton=true}}{{paper-icon 'expand_less'}}{{/paper-button}}
        {{/actions.icons}}
      {{/card.actions}}
      {{#card.content}}
        <p>
          The titles of Washed Out's breakthrough song and the first single from Paracosm share the
          two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
        </p>
      {{/card.content}}
    {{/paper-card}}
  {{/each}}

  </div>
  </div>
`

**Comment by rmmmp** [comment]
@BobrImperator, I notice in your `model()` code that you're not returning the query result. It should be like this:

```javascript
model() {
  // Make sure that you're returning the query promise
  return this.get('store').query('image', { limitToFirst: 10 });
}
```

Then at some point in your app (maybe in controller) do `this.get('model').get('firebase').next(10)`.

**Comment by BobrImperator** [comment]
So... I got it going! Thank you very much! But there's one thing.
CacheId is necessary if model wants to use firebase on it.
`model() {
  // Make sure that you're returning the query promise
  return this.get('store').query('image', { limitToFirst: 10 });
}`

**Comment by BobrImperator** [comment]
```
model() {

  // Make sure that you're returning the query promise

  return this.get('store').query('image', { limitToFirst: 10 });

}
```
Was getting me 

> TypeError: Cannot read property 'next' of undefined

So I just added CacheId

` return this.get('store').query('image', { limitToFirst: 10,cacheId: 'hello' });`

While component which loads data looks like this
```
  actions: {

  loadMore(){

    return this.get('model').get('firebase').next(10)

  }
}

```

I also use ember-simple-infinite-scroller to get a trigger for that action.
@rmmmp Thank you very much!

**Comment by rmmmp** [comment]
@BobrImperator, ah yes you need to add `cacheId` which you already did. Sorry for missing that out. I'm inclined to think that this isn't a problem in the addon since you've said that the models are getting loaded in ember-inspector.

Is it only the next 10 data that's not showing, or is it every data? Maybe you can try displaying the original data first without loading the next 10.

**Comment by BobrImperator** [comment]
```
model() { 

this.get('store').query('image', { 
cacheId: 'hello', limitToFirst: 10 }).then((images) => {
images.get('firebase').next(10) 

});
```
With this in route - just like I had it done previously, the page was completely blank, and inspector would show all possible data, just like this.store.findAll('image') which is even better than it was before, because before it was only limitedToFirst 10, just like in query parameter.

and oh, at this point I also have
>Ember      : 2.14.1
Ember Data : 2.14.10
Firebase   : 3.9.0
EmberFire  : 0.0.0 - in package.json ^2.0.7
jQuery     : 3.2.1

```
this.get('store').query('image', { 
cacheId: 'hello', limitToFirst: 10 })
```
This of course displays first 10, and no more data.

Hope it helps you, also Thank you for your time.

**Comment by rmmmp** [comment]
If data are inside ember-inspector but your templates are still not displaying the data then it must be an issue with how you're implementing your codes. At this point, I can't pinpoint what's the wrong thing that you're doing. I'll need to see the repository of your app itself if possible.

At any case, you should make sure that your `model()` is returning the `query()` promise and that you're passing in the `model` attribute to the component that will display it.

**Comment by BobrImperator** [comment]
https://github.com/BobrImperator/ember-shrink-fire/tree/sideBar
It's not on master branch yet, all my "experiments" with ember-fire utils are on sideBar branch.
Currently Adapter is emberfire's because I couldn't figure out how to save relationships in emberfire-utils way, so ultimately I am not using infinite scrolling for now.

**Comment by rmmmp** [comment]
@BobrImperator, that's weird. Your code seems to look fine. Have you tried just doing an `{{#each}}` without any of the `{{infinite-scroller}}` and all ember-paper related components?

As for saving relationships, see [here](https://github.com/rmmmp/emberfire-utils#relationship-wont-get-updated-when-firing-save).

**Comment by BobrImperator** [comment]
Hello, sorry for my absence, didn't give you  a reply for so long.
My code is working properly ever since 4 days ago, when you told me to query with options on route, and then tell firebase to load next inside component's action.

But I dunno if I've lost track of thing that you'd want me to check on, sadly programming is just a hobby, and I had other work to do. But 
`{{#each model as |model|}}
  <img src={{model.url}} />
{{/each}}
`
Displays model data just fine, but of course is limited because there's no trigger, but when it get's triggered, it does load next 10.

**Comment by rmmmp** [comment]
@BobrImperator, I see. I didn't realized this was already fixed! 😀
