### ISSUE TITLE
cacheid

### ISSUE THREAD

**Issue by bitbreakr** [rmmmp/emberfire-utils#60]
Hello guys,

Sorry for this dumb question of mine but i don't know how to use cacheId.

Is it possible to get any help on this ?

Thanks in advance

:)

**Comment by mikkopaderes** [comment]
It's just a unique ID that you provide on your own. When you initiate another query with the same cacheId, it will return the result of the previous query (not making another network request to firebase

**Comment by heat** [comment]
Using with cacheId I got a error.
`Error while processing route: ... TypeError: Cannot read property 'set' of undefined Error: TypeError: Cannot read property 'set' of undefined. `. Since I remove it's back to work.

```
return this.get('store').query('my-model', {
        cacheId: 'my_cache_id',
        path: '/models'
      });`
```

**Comment by bitbreakr** [comment]
@heat Same issue here.
